
apiVersion: apps/v1
kind: Deployment
metadata:
name: nodejs-deployment
spec:
replicas: 2
template:
metadata:
labels:
app: nodejs
spec:
containers:
- name: nodongo
image: registry-1.docker.io/virtuallionel2/se_lionel_2_0:3
ports:
- containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: autonomous-nj
spec:
  type: NodePort #Exposes the service as a node port
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: autonomous-nodejs