apiVersion: apps/v1
kind: Deployment
metadata: 
  name: autonomous-nj
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: autonomous-nodejs
  template: 
    metadata: 
      labels: 
        app: autonomous-nodejs
    spec: 
      containers: 
          image: "registry-1.docker.io/virtuallionel2/se_lionel_2_0:3"
          name: autonomous-nodejscnt
          ports: 
              containerPort: 80